version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
    ignore:
      - dependency-name: "django"
        versions: ["3.x"]
